package com.modrajat.authservice.correctmodel;


/**
 * Authorization Server redirects
 * the user agent back to the redirect_url provided by the client.
 *
 *      HTTP/1.1 302 Found
 *      Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA
 *                &state=xyz
 */
public class AuthorizationResponse {

    /**
     * Authorization Code is generated by Authorization Server.
     * Code should expire shortly after issuing it.
     * Client can not use same Auth Code multiple times,
     * Auth Server should deny the request.
     *
     * Authorization Code is bound to clientId and redirect_url
     */

    String code;

    //To avoid cross site scripting somehow
    String state;

    /**
     * Not Handling Error response right now
     *
     HTTP/1.1 302 Found
     Location: https://client.example.com/cb?error=access_denied&state=xyz
     */
}
